config/routes.rb
Rails.application.routes.draw do
  constraints(Subdomain) do
    get '/' => 'blog/posts#index', :as => 'site_posts'
    get '/posts/:id' => 'blog/posts#show', :as => 'site_post'
    get '/categories/:id' => 'blog/categories#index', :as => 'site_category'
    get '/tags/:id' => 'blog/posts#tag_cloud'
    get '/feed' => 'blog/posts#feed'
  end 

  root to: 'visitors#index'
  devise_for :users
  resources :users
  get 'blog/dashboard' => 'dashboard#index', :as => 'dashboards'
  get 'blog/:subdomain/dashboard' => 'dashboard#index', :as => 'dashboard'
  resources :blogs do
    resources :posts do
      get 'revert', :on => :member
      post 'preview', :on => :member
    end
    resources :categories
  end

end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  before_filter :authenticate_user!
  after_action :verify_authorized
  before_action :find_blog
  layout "dashboard_site"

  def find_blog
    if params[:subdomain]
      @current_blog = current_user.blogs.find_by(:subdomain => params[:subdomain])
    else
      @current_blog = current_user.blogs.first
    end
  end

  def index
    authorize Blog
    if @current_blog.blank?
      redirect_to new_blog_path, :alert => "Create a blog first."
      return
    end
    @posts = @current_blog.posts.all
    @post = @current_blog.posts.new
  end
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/views/dashboard/index.html.erb
<%= render 'layouts/dashboard/toolbar' %>
<hr>
<div>
  <table class="table">
    <thead>
      <tr>
        <th>Date</th>
        <th>Title</th>
        <th>Status</th>
        <th>&nbsp;</th>
      </tr>
    </thead>
    <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= localize(post.publish_date, :format => :long) %></td>
        <td><%= post.title %></td>
        <td><%= post.status %></td>
        <td><%= link_to 'Edit', edit_blog_post_path(@current_blog, post), 'data-no-turbolink' => true %></td>
        <td><%= link_to 'Remove', blog_post_path(@current_blog, post), :method => :delete %></td>
      </tr>
    <% end %>
    </tbody>
  </table>
</div>