config/routes.rb
Rails.application.routes.draw do
  constraints(Subdomain) do
    get '/' => 'blog/posts#index', :as => 'site_posts'
    get '/posts/:id' => 'blog/posts#show', :as => 'site_post'
    get '/categories/:id' => 'blog/categories#index', :as => 'site_category'
    get '/tags/:id' => 'blog/posts#tag_cloud'
    get '/feed' => 'blog/posts#feed'
  end 

  root to: 'visitors#index'
  devise_for :users
  resources :users
  get 'blog/dashboard' => 'dashboard#index', :as => 'dashboards'
  get 'blog/:subdomain/dashboard' => 'dashboard#index', :as => 'dashboard'
  resources :blogs do
    resources :posts do
      get 'revert', :on => :member
      post 'preview', :on => :member
    end
    resources :categories
  end

end

app/models/blog.rb
class Blog < ActiveRecord::Base
  belongs_to :user
  has_many :posts, :dependent => :destroy
  has_many :categories, :dependent => :destroy
  validates_presence_of :subdomain, :title
  validates_uniqueness_of :subdomain
  validates_uniqueness_of :fqdn, :allow_blank => true, :allow_nil => true
  validates_format_of :subdomain, :with => /\A[a-z][a-z0-9]{2,17}\z/i
  validates_exclusion_of :subdomain, :in => [
    "www",
    "api",
    "help",
    "mail"
  ]

  def to_param
    subdomain
  end
end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :blog
  has_many :post_categoryships, :dependent => :destroy
  has_many :categories, :through => :post_categoryships
  accepts_nested_attributes_for :categories
  after_initialize :assign_values
  chinese_permalink :title
  validates_presence_of :title
  acts_as_taggable

  enum status: [:draft, :publish]

  default_scope { where(:deleted => false).order('publish_date DESC') }
  scope :publish, -> { where(:status => self.statuses[:publish]) }

  def assign_values
    self.publish_date ||= Time.now
  end

  def to_param
    return "#{id}" if permalink.blank?
    "#{id}-#{permalink}"
  end
end

app/controllers/blog/application_controller.rb
class Blog::ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_filter :find_blog
  layout "blog_site"

  def find_blog
    case request.host
    when Rails.application.secrets.domain_name, nil
    else     
      if request.host.index(Rails.application.secrets.domain_name)
        @current_blog = Blog.find_by_subdomain(request.host.split('.').first)
      else
        @current_blog = Blog.find_by_fqdn(request.host)
      end

      if !@current_blog
        redirect_to Rails.application.secrets.domain_name
      end

    end  
  end

  def per_page
    @current_blog.per_page || 10
  end
end

app/controllers/blog/categories_controller.rb
class Blog::CategoriesController < Blog::PostApplicationController
  def index
    @category = @current_blog.categories.find_by(:name => params[:id])
    @posts = @category.posts.publish.page(params[:page]).per(per_page)
    @categories = @current_blog.categories.all
    @tags = @current_blog.posts.tag_counts_on(:tags)

    render template: "blog/posts/categories"
  end
end

app/controllers/blog/post_application_controller.rb
class Blog::PostApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_filter :find_blog
  layout "blog_site"

  def find_blog
    case request.host
    when Rails.application.secrets.domain_name, nil
    else     
      if request.host.index(Rails.application.secrets.domain_name)
        @current_blog = Blog.find_by_subdomain(request.host.split('.').first)
      else
        @current_blog = Blog.find_by_fqdn(request.host)
      end

      if !@current_blog
        redirect_to Rails.application.secrets.domain_name
      end

    end  
    @current_blog.image_url = ActionController::Base.helpers.asset_path('intro-bg.jpg') if @current_blog.image_url.blank?
  end

  def per_page
    @current_blog.per_page || 10
  end
end

app/controllers/blog/posts_controller.rb
class Blog::PostsController < Blog::PostApplicationController
  def index
    @posts = @current_blog.posts.publish.page(params[:page]).per(per_page)
    @categories = @current_blog.categories.all
    @tags = @current_blog.posts.tag_counts_on(:tags)
  end

  def feed
    @posts = @current_blog.posts.publish.page(params[:page]).limit(20)

    respond_to do |format|
      format.rss { render :layout => false }
    end
  end

  def show
    @post = @current_blog.posts.publish.find(params[:id])
    @categories = @current_blog.categories.all
    @tags = @current_blog.posts.tag_counts_on(:tags)
  end

  def tag_cloud
    @current_tags = params[:id].split(',')
    @posts = @current_blog.posts.tagged_with(@current_tags).publish.page(params[:page]).per(per_page)
    @categories = @current_blog.categories.all
    @tags = @current_blog.posts.tag_counts_on(:tags)
    @rel_tags = @current_blog.posts.tagged_with(@current_tags).tag_counts_on(:tags)

    render template: "blog/posts/categories"
  end
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  before_filter :authenticate_user!
  after_action :verify_authorized
  layout "dashboard_site"

  def index
    @blogs = current_user.blogs.all
    authorize Blog
  end

  def new
    @blog = current_user.blogs.new
    authorize @blog
  end

  def create
    @blog = current_user.blogs.new(secure_params)
    authorize @blog
    if @blog.save
      redirect_to dashboard_path(@blog), :notice => "Blog added."
    else
      render :new
    end
  end

  def show
    @blog = current_user.blogs.find_by(:subdomain => params[:id])
    authorize @blog
  end

  def edit
    @blog = current_user.blogs.find_by(:subdomain => params[:id])
    @current_blog = @blog.dup
    @current_blog.filepicker_key = ENV['FILEPICKER_KEY'] if @current_blog.filepicker_key.blank?
    authorize @blog
  end

  def update
    @blog = current_user.blogs.find_by(:subdomain => params[:id])
    authorize @blog
    if @blog.update_attributes(secure_params)
      redirect_to edit_blog_path(@blog), :notice => "Blog updated."
    else
      render :edit, :alert => "Unable to update blog."
    end
  end

  def destroy
    blog = current_user.blogs.find_by(:subdomain => params[:id])
    authorize blog
    blog.destroy
    redirect_to blogs_path, :notice => "Blog deleted."
  end

  private

  def secure_params
    params.require(:blog).permit(:title, :subtitle, :description, :subdomain, :fqdn, :filepicker_key, :disqus_key, :ga_key, :per_page, :image_url, :facebook_button, :twitter_button, :google_button)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_filter :authenticate_user!
  after_action :verify_authorized
  before_action :find_blog
  layout "dashboard_site"

  def find_blog
    @current_blog = current_user.blogs.find_by(:subdomain => params[:blog_id])
    @current_blog.filepicker_key = ENV['FILEPICKER_KEY'] if @current_blog.filepicker_key.blank?
  end

  def new
    @post = @current_blog.posts.new
    authorize @post
    @categories = @current_blog.categories.all
  end

  def create
    @post = @current_blog.posts.new(secure_params)
    authorize @post
    if @post.save
      redirect_to edit_blog_post_path(@current_blog, @post)
    else
      redirect_to dashboard_path(@current_blog), :notice => "Unable to add post."
    end
  end

  def edit
    @post = @current_blog.posts.find(params[:id])
    authorize @post
    @categories = @current_blog.categories.all
  end

  def update
    @post = @current_blog.posts.find(params[:id])
    authorize @post
    if @post.update_attributes(secure_params)
      redirect_to dashboard_path(@current_blog), :notice => "Post updated."
    else
      render :edit
    end
  end

  def destroy
    post = @current_blog.posts.find(params[:id])
    authorize post
    post.deleted = true
    if post.save
      redirect_to dashboard_path(@current_blog), :notice => "Post destroyed. #{ActionController::Base.helpers.link_to 'Undo', revert_blog_post_path(:id => post.id)}"
    else
      redirect_to dashboard_path(@current_blog), :notice => "Unable to destroy post."
    end
  end

  def revert
    post = @current_blog.posts.unscoped.find(params[:id])
    authorize post, :destroy?
    post.deleted = false
    if post.save
      redirect_to dashboard_path(@current_blog), :notice => "Post reverted."
    else
      redirect_to dashboard_path(@current_blog), :notice => "Unable to revert post."
    end
  end

  def preview
    post = @current_blog.posts.find(params[:id])
    authorize post, :index?
    render layout: false
  end

  def secure_params
    params.require(:post).permit(:publish_date, :title, :permalink, :status, :tag_list, :content, :category_ids => [], :categories_attributes => [:id, :name])
  end
end

app/helpers/blog/categories_helper.rb
module Blog::CategoriesHelper
end

app/helpers/blog/posts_helper.rb
module Blog::PostsHelper
  include ActsAsTaggableOn::TagsHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/blog/posts/categories.html.erb
<% if @current_tags and @rel_tags.any? %>
  <div class="tags-bar">
    <i class="fa fa-tags"></i>
    <% @current_tags.each do |tag| %>
      <% remove_tag = @current_tags - [tag] %>
      <% if remove_tag.any? %>
        <%= link_to sanitize("#{tag} <i class=\"glyphicon glyphicon-remove\"></i>"), { :action => :tag_cloud, :id => (@current_tags - [tag]).join(',') }, :class => 'label label-success' %>
      <% else %>
        <%= link_to sanitize("#{tag} <i class=\"glyphicon glyphicon-remove\"></i>"), site_posts_path, :class => 'label label-success' %>
      <% end %>
    <% end %>
    <% @rel_tags.each do |tag| %>
      <% next if @current_tags.include? tag.name %>
      <%= link_to tag.name, { :action => :tag_cloud, :id => @current_tags.push(tag.name).join(',') }, :class => 'label label-primary' %>
    <% end %>
  </div>
<% end %>
<% if @category %>
  <p><h3>Category: <%= @category.name %></h3></p>
<% end %>
<hr>
<!-- Blog Entries Column -->
<div class="col-md-12">
  <ul>
  <% @posts.each do |post| %>
    <li>
      <span><%= localize(post.publish_date, :format => :long) %></span>
      <span><%= link_to post.title, site_post_path(post), 'data-no-turbolink' => true %></span>
      </li>
  <% end %>
  </ul>

  <!-- Pager -->
  <ul class="pager">
    <li class="previous">
    <%= link_to_next_page @posts, sanitize("&larr; Older") %>
    </li>
    <li class="next">
    <%= link_to_previous_page @posts, sanitize("Newer &rarr;") %>
    </li>
  </ul>

</div>

app/views/blog/posts/index.html.erb
<% if @current_tags and @rel_tags != @current_tags %>
  <div class="tags-bar">
    <i class="fa fa-tags"></i>
    <%= @current_tags.join(' ') %>
    <% @rel_tags.each do |tag| %>
      <% next if @current_tags.include? tag.name %>
      <%= link_to tag.name, { :action => :tag_cloud, :id => @current_tags.push(tag.name).join(',') } %>
    <% end %>
  </div>
<% end %>
<!-- Blog Entries Column -->
<div class="col-md-12">
  <% @posts.each do |post| %>
    <section>
    <h1>
      <%= link_to post.title, site_post_path(post), 'data-no-turbolink' => true %>
    </h1>
    <p class="lead">
    by <%= @current_blog.user.name %>
    </p>
    <p><span class="glyphicon glyphicon-time"></span> Posted on <%= localize(post.publish_date, :format => :long) %></p>
    <hr>
    <% post_contents = post.content.split('<!--more-->') %>
    <%= markdown(post_contents.first).html_safe if post_contents.first %>
    <% if post_contents.count > 1 %>
    <a class="btn btn-primary" href="<%= site_post_path(post) %>" data-no-turbolink=" true">Read More <span class="glyphicon glyphicon-chevron-right"></span></a>
    <% end %>

    </section>
    <hr>
    <div class="misc-bar">
      <% if not @current_blog.disqus_key.blank? %>
      <i class="fa fa-comment"></i> <%= link_to 'Comments', "#{site_post_url(post)}#disqus_thread", 'data-no-turbolink' => true %>
      <% end %>
    </div>
  <% end %>

  <!-- Pager -->
  <ul class="pager">
    <li class="previous">
    <%= link_to_next_page @posts, sanitize("&larr; Older") %>
    </li>
    <li class="next">
    <%= link_to_previous_page @posts, sanitize("Newer &rarr;") %>
    </li>
  </ul>

</div>
<% content_for :javascript do %>
  <% if not @current_blog.disqus_key.blank? %>
   <script type="text/javascript">
    /* * * CONFIGURATION VARIABLES: EDIT BEFORE PASTING INTO YOUR WEBPAGE * * */
     var disqus_shortname = '<%= @current_blog.disqus_key %>'; // required: replace example with your forum shortname

    /* * * DON'T EDIT BELOW THIS LINE * * */
    (function () {
        var s = document.createElement('script'); s.async = true;
        s.type = 'text/javascript';
        s.src = '//' + disqus_shortname + '.disqus.com/count.js';
        (document.getElementsByTagName('HEAD')[0] || document.getElementsByTagName('BODY')[0]).appendChild(s);
    }());
    </script>
  <% end %>
<% end %>

app/views/blog/posts/show.html.erb
<% content_for :title, "#{@post.title} | #{@current_blog.title}" %>
<% content_for :description, truncate(strip_tags(markdown(@post.content).html_safe), :length => 150) %>
<!-- Blog Post Content Column -->
<div class="col-md-12">
  <!-- Blog Post -->
  <article>

  <!-- Title -->
  <h1><%= @post.title %></h1>

  <!-- Author -->
  <p class="lead">
  by <%= @current_blog.user.name %>
  </p>

  <!-- Date/Time -->
  <p><span class="glyphicon glyphicon-time"></span> Posted on <%= localize(@post.publish_date, :format => :long) %></p>
  <% if @post.tag_list.any? %>
  <p>
    <i class="fa fa-tags"></i>
    <% @post.tag_list.each do |tag| %>
      <%= link_to tag, { :action => :tag_cloud, :id => tag } %>
    <% end %>
  </p>
  <% end %>
  <hr>

  <!-- Post Content -->
  <%= markdown(@post.content).html_safe %>

  </article>
  <hr>
  <div class="social-buttons">
    <%= like_button('mdtyper') if @current_blog.facebook_button %>
    <%= tweet_button(via: nil, count: 'horizontal') if @current_blog.twitter_button %>
    <%= google_plus_button(size: 'medium', annotation: 'bubble', script: true) if @current_blog.google_button %>
  </div>

  <% if not @current_blog.disqus_key.blank? %>
  <!-- Blog Comments -->
  <div id="disqus_thread"></div>
  <script type="text/javascript">
    /* * * CONFIGURATION VARIABLES: EDIT BEFORE PASTING INTO YOUR WEBPAGE * * */
  var disqus_shortname = '<%= @current_blog.disqus_key %>';

  /* * * DON'T EDIT BELOW THIS LINE * * */
  (function() {
   var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;
   dsq.src = '//' + disqus_shortname + '.disqus.com/embed.js';
   (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dsq);
   })();
</script>
<noscript>Please enable JavaScript to view the <a href="http://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>
<a href="http://disqus.com" class="dsq-brlink">comments powered by <span class="logo-disqus">Disqus</span></a>

  <!-- Posted Comments -->
  <% end %>

</div>