config/routes.rb
Rails.application.routes.draw do
  constraints(Subdomain) do
    get '/' => 'blog/posts#index', :as => 'site_posts'
    get '/posts/:id' => 'blog/posts#show', :as => 'site_post'
    get '/categories/:id' => 'blog/categories#index', :as => 'site_category'
    get '/tags/:id' => 'blog/posts#tag_cloud'
    get '/feed' => 'blog/posts#feed'
  end 

  root to: 'visitors#index'
  devise_for :users
  resources :users
  get 'blog/dashboard' => 'dashboard#index', :as => 'dashboards'
  get 'blog/:subdomain/dashboard' => 'dashboard#index', :as => 'dashboard'
  resources :blogs do
    resources :posts do
      get 'revert', :on => :member
      post 'preview', :on => :member
    end
    resources :categories
  end

end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  before_filter :authenticate_user!
  after_action :verify_authorized
  before_action :find_blog
  layout "dashboard_site"

  def find_blog
    if params[:subdomain]
      @current_blog = current_user.blogs.find_by(:subdomain => params[:subdomain])
    else
      @current_blog = current_user.blogs.first
    end
  end

  def index
    authorize Blog
    if @current_blog.blank?
      redirect_to new_blog_path, :alert => "Create a blog first."
      return
    end
    @posts = @current_blog.posts.all
    @post = @current_blog.posts.new
  end
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/views/layouts/dashboard/_blog_toolbar.html.erb
<div class="btn-toolbar" role="toolbar">
  <div class="btn-group">
    <a href="<%= edit_blog_path(current_blog) %>" class="btn btn-default <%= 'active' if params[:controller] == 'blogs' and params[:action] == 'edit' %>">
      Settings
    </a>
    <a href="<%= blog_categories_path(current_blog) %>" class="btn btn-default <%= 'active' if params[:controller] == 'categories' %>">
      Categories
    </a>
  </div>
</div>

app/views/layouts/dashboard/_footer.html.erb
        <footer class="footer">
            <div class="row">
                <div class="col-lg-12">
                  <p>Copyright &copy; <%= Rails.application.secrets.app_name %> 2014. All Rights Reserved</p>
                </div>
                <!-- /.col-lg-12 -->
            </div>
            <!-- /.row -->
        </footer>

app/views/layouts/dashboard/_navigation.html.erb
<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to Rails.application.secrets.app_name, root_path, class: 'navbar-brand' %>
    </div>
    <div class="collapse navbar-collapse">
      <% if @current_blog %>
      <p class="navbar-text"> &gt; </p>
      <p class="navbar-text"><%= link_to @current_blog.title, dashboard_path(@current_blog), :class => 'navbar-link' %></p>
      <% end %>
      <ul class="nav navbar-nav navbar-right">
        <%= render 'layouts/navigation_links' %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/dashboard/_toolbar.html.erb
<div class="btn-toolbar" role="toolbar">
  <div class="btn-group">
    <button class="btn btn-default" data-toggle="modal" data-target="#addPostModal">
      <span class="glyphicon glyphicon-plus"></span> Add post
    </button>
    <a href="//<%= @current_blog.fqdn.blank? ? "#{@current_blog.subdomain}.#{Rails.application.secrets.domain_name}" : @current_blog.fqdn %>" class="btn btn-default" target="_blank">
      <span class="glyphicon glyphicon-cog"></span> Visit blog
    </a>
    <a href="<%= edit_blog_path(@current_blog) %>" class="btn btn-default">
      <span class="glyphicon glyphicon-cog"></span> Edit blog
    </a>
  </div>
</div>

<!-- Modal -->
<div class="modal fade" id="addPostModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <%= simple_form_for @post, :url => blog_posts_path(@current_blog) do |f| %>
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
        <h4 class="modal-title" id="myModalLabel">New post</h4>
      </div>
      <div class="modal-body">
        <%= f.input :title %>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        <%= f.submit :class => 'btn btn-primary' %>
      </div>
      <% end %>
    </div>
  </div>
</div>

<script>
  $('#addPostModal').on('shown.bs.modal', function () {
    $('#post_title').focus();
  })
</script>