config/routes.rb
Rails.application.routes.draw do
  constraints(Subdomain) do
    get '/' => 'blog/posts#index', :as => 'site_posts'
    get '/posts/:id' => 'blog/posts#show', :as => 'site_post'
    get '/categories/:id' => 'blog/categories#index', :as => 'site_category'
    get '/tags/:id' => 'blog/posts#tag_cloud'
    get '/feed' => 'blog/posts#feed'
  end 

  root to: 'visitors#index'
  devise_for :users
  resources :users
  get 'blog/dashboard' => 'dashboard#index', :as => 'dashboards'
  get 'blog/:subdomain/dashboard' => 'dashboard#index', :as => 'dashboard'
  resources :blogs do
    resources :posts do
      get 'revert', :on => :member
      post 'preview', :on => :member
    end
    resources :categories
  end

end

app/views/layouts/_gtm.html.erb
<% if not ENV['GOOGLE_TAG_MANAGER'].blank? %>
<!-- Google Tag Manager -->
<noscript><iframe src="//www.googletagmanager.com/ns.html?id=GTM-T5Q8CZ"
height="0" width="0" style="display:none;visibility:hidden"></iframe></noscript>
<script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
'//www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
})(window,document,'script','dataLayer','<%= ENV['GOOGLE_TAG_MANAGER'] %>');</script>
<!-- End Google Tag Manager -->
<% end %>

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 3.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, sanitize(msg), :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<%# navigation styled for Bootstrap 3.0 %>
<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to Rails.application.secrets.app_name, root_path, class: 'navbar-brand' %>
    </div>
    <div class="collapse navbar-collapse pull-right">
      <ul class="nav navbar-nav">
        <%= render 'layouts/navigation_links' %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>
<% if user_signed_in? %>
  <li><%= link_to 'Dashboard', dashboards_path %></li>
  <li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown"><%= current_user.name %><span class="caret"></span></a>
  <ul class="dropdown-menu" role="menu">
    <% if current_user.admin? %>
      <li><%= link_to 'Users', users_path %></li>
    <% end %>
    <li><%= link_to 'Edit account', edit_user_registration_path %></li>
    <li class="divider"></li>
    <li><%= link_to 'Sign out', destroy_user_session_path, :method=>'delete' %></li>
  </ul>
  </li>
<% else %>
  <li><%= link_to 'Sign in', new_user_session_path %></li>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : Rails.application.secrets.app_name %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : Rails.application.secrets.app_name %>">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <%= render 'layouts/gtm' %>
    <%= render 'layouts/messages' %>
    <%= render 'layouts/navigation' %>
    <%= yield %>
    <!-- Footer -->
    <footer>
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <ul class="list-inline">
                        <li>
                        <a href="http://blog.<%= Rails.application.secrets.domain_name %>">Blog</a>
                        </li>
                        <li class="footer-menu-divider">&sdot;</li>
                        <li>
                        <a href="mailto:hi@<%= Rails.application.secrets.domain_name %>">Contact</a>
                        </li>
                    </ul>
                    <p class="copyright text-muted small">Copyright &copy; <%= Rails.application.secrets.app_name %> 2014. All Rights Reserved</p>
                </div>
            </div>
        </div>
    </footer>
  </body>
</html>

app/views/layouts/blog_site.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : @current_blog.title %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : @current_blog.description %>">
    <%= stylesheet_link_tag 'blog_home', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    <link href="/feed.rss" rel="alternate" title="<%= @current_blog.title %>" type="application/rss+xml">
    <% if not @current_blog.image_url.blank? %>
    <style>
      .intro-header {
        background: url('<%= @current_blog.image_url %>') no-repeat center center;
        background-size: cover;
        height: 400px;
      }
    </style>
    <% end %>
  </head>
  <body>
    <div id="wrapper">
    <header class="header">
      <a href="#sidebar-toggle" id="sidebar-toggle" class="pull-left"><span class="glyphicon glyphicon-list"></span></a>
      <h1 class="page-header">
        <%= link_to @current_blog.title, site_posts_path, 'data-no-turbolink' => true %>
        <small class="hidden-xs"><%= @current_blog.subtitle %></small>
      </h1>
    </header>
    <!-- Sidebar -->
    <%= render 'layouts/blog/categories' %>
    <div class="intro-header"></div>
    <!-- Page Content -->
    <div class="container">

        <div class="row">

            <%= yield %>

        </div>
        <!-- /.row -->

        <hr>

        <!-- Footer -->
        <%= render 'layouts/blog/footer' %>

    </div>
    <!-- /.container -->
    </div>
    <%= javascript_include_tag 'blog_site', 'data-turbolinks-track' => true %>
    <% if not @current_blog.ga_key.blank? %>
    <script>
      (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
      (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
      m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
      })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

      ga('create', '<%= @current_blog.ga_key %>', 'auto');
      ga('send', 'pageview');

    </script>
    <% end %>
    <%= yield :javascript %>
  </body>
</html>

app/views/layouts/dashboard_site.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : Rails.application.secrets.app_name %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : Rails.application.secrets.app_name %>">
    <%= stylesheet_link_tag 'dashboard', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <%= render 'layouts/gtm' %>
    <%= render 'layouts/messages' %>
<!-- Navigation -->
    <%= render 'layouts/dashboard/navigation' %>

    <!-- Page Content -->
    <div class="container">

        <div class="row">

            <%= yield %>

        </div>
        <!-- /.row -->

        <!-- Footer -->
        <%= render 'layouts/dashboard/footer' %>

    </div>
    <!-- /.container -->
    <script type="text/javascript" src="//api.filepicker.io/v1/filepicker.js"></script>
    <% if @current_blog %>
      <script type="text/javascript">filepicker.setKey('<%= @current_blog.filepicker_key %>');</script>
    <% else %>
      <script type="text/javascript">filepicker.setKey('<%= ENV['FILEPICKER_KEY'] %>');</script>
    <% end %>
    <%= javascript_include_tag 'dashboard', 'data-turbolinks-track' => true %>
    <%= yield :javascript %>
  </body>
</html>